### ISSUE TITLE
Manual page

### ISSUE THREAD

**Issue by bbwanjia** [iewnfod/CAIE_Code#3]
### 功能描述

A good code interpreter should have a manual page which can be easily accessed from the shell view.
However when I tried `$ man cpc` I got this
<img width="478" alt="Screenshot 2023-09-08 at 16 08 48" src="https://github.com/iewnfod/CAIE_Code/assets/90976035/3bc7664d-eea6-49cd-973f-370a2bea4b08">
Hopefully the author could add the manual from standard `man` command; the shown manual page could be the same as the output from `$ cpc -h`.

### 功能样例

`$ man cpc`
<img width="882" alt="Screenshot 2023-09-08 at 16 15 03" src="https://github.com/iewnfod/CAIE_Code/assets/90976035/6e32eba5-49a5-4f06-b758-df3caf6a5552">

**Comment by iewnfod** [comment]
I'm trying to do this now, but it seems a little bit difficult for me, since I've never written a man before.

**Comment by iewnfod** [comment]
I have finished the writing of the man file. If you really need this feature, you can add that file into your MANPATH by yourself and then you can use `man cpc`. But, I cannot let the install script to write this file into the target path automatically because MacOS refuses to let me write anything into `/usr/share/man/man1`, even though I got the root permission, and I think `-h` is much easier to use.
